env:
  browser: true
  es2021: true

plugins:
  - '@typescript-eslint'
  - import
  - jsx-a11y
  - react
  - react-hooks

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true

  ecmaVersion: latest
  sourceType: module

settings:
  react:
    version: detect

rules:
  jsx-a11y/media-has-caption: 0
  react/prop-types: 0
  import/no-unresolved: 0
